export const YOUTUBE_VIDEO_FORMATS = ["long_form", "short", "livestream_outline", "community_post", "playlist_intro"] as const;
export const YOUTUBE_VIDEO_TYPES = ["character_analysis", "item_analysis", "technique_analysis", "realm_explanation", "sect_explanation", "location_explanation", "event_recap", "comparison", "lore_explainer", "timeline_analysis", "beginner_guide", "top_list", "hidden_detail", "story_arc_explainer", "custom"] as const;
export const YOUTUBE_PRODUCTION_STATUSES = ["idea", "scripting", "script_ready", "thumbnail_ready", "voice_over_ready", "editing", "ready_to_upload", "uploaded", "archived"] as const;
export const YOUTUBE_STATUSES = ["draft", "scheduled", "published", "unlisted", "private", "archived"] as const;
export const THUMBNAIL_LAYOUTS = ["character_closeup", "artifact_focus", "split_comparison", "battle_scene", "mysterious_silhouette", "sect_background", "text_heavy", "cinematic_scene"] as const;

export type YouTubeVideo = { id:string; novel_id:string; source_script_id:string|null; source_content_idea_id:string|null; source_series_id:string|null; video_format:string; title:string; working_title:string|null; video_type:string; duration_target_minutes:number|null; duration_target_seconds:number|null; audience_level:string; tone:string; style:string; script_text:string|null; script_json:any; hook:string|null; intro:string|null; body:string|null; conclusion:string|null; chapters_json:any[]; thumbnail_prompts_json:any[]; seo_metadata_json:any; shorts_cutdowns_json:any[]; source_references_json:any[]; fact_check_status:string; visual_check_status:string; production_status:string; youtube_status:string; created_at:string; updated_at:string };
export type YouTubeSeoPackage = { id:string; youtube_video_id:string; novel_id:string; primary_title:string; alternative_titles_json:string[]; description:string|null; tags_json:string[]; hashtags_json:string[]; chapters_text:string|null; pinned_comment:string|null; playlist_suggestion:string|null; target_keywords_json:string[]; search_intent:string|null; seo_score:number; click_score:number; retention_score:number; warning_notes_json:string[]; created_at:string; updated_at:string };
export type YouTubeThumbnailConcept = { id:string; youtube_video_id:string; novel_id:string; title:string; concept_summary:string|null; thumbnail_text:string|null; image_prompt:string; negative_prompt:string|null; layout_type:string; emotion_angle:string|null; visual_style_preset:string; source_references_json:any[]; warning_notes_json:string[]; created_at:string; updated_at:string };
export type YouTubeShortCutdown = { id:string; youtube_video_id:string; novel_id:string; title:string; short_hook:string|null; source_start_time:string|null; source_end_time:string|null; duration_seconds:number; short_script:string|null; image_prompt:string|null; video_prompt:string|null; caption:string|null; hashtags_json:string[]; source_reference:any; status:string; created_at:string; updated_at:string };
export type YouTubePlaylist = { id:string; novel_id:string; title:string; description:string|null; playlist_type:string; target_audience:string; video_order_strategy:string; status:string; created_at:string; updated_at:string };
