import { getSupabaseServerClient } from "@/lib/supabase/server";
import { getPlannerContext } from "@/lib/module5-data";
import { createJsonChatCompletion, parseAIJson } from "@/lib/ai/openaiClient";
import { buildGenerateYouTubeLongFormPrompt } from "@/lib/ai/prompts/youtube/generateYouTubeLongFormPrompt";
import { buildGenerateYouTubeShortPrompt } from "@/lib/ai/prompts/youtube/generateYouTubeShortPrompt";
import { buildGenerateYouTubeSeoPackagePrompt } from "@/lib/ai/prompts/youtube/generateYouTubeSeoPackagePrompt";
import { buildGenerateYouTubeThumbnailPrompt } from "@/lib/ai/prompts/youtube/generateYouTubeThumbnailPrompt";
import { buildRepurposeLongFormToShortsPrompt } from "@/lib/ai/prompts/youtube/repurposeLongFormToShortsPrompt";
import { buildGenerateYouTubePlaylistPrompt } from "@/lib/ai/prompts/youtube/generateYouTubePlaylistPrompt";
import { buildYouTubeUploadChecklistPrompt } from "@/lib/ai/prompts/youtube/youtubeUploadChecklistPrompt";
import type { YouTubeVideo } from "@/lib/module6-types";

export async function listYouTubeVideos(novelId:string){const{data,error}=await getSupabaseServerClient().from("youtube_videos").select("*").eq("novel_id",novelId).order("created_at",{ascending:false}); if(error)throw error; return data as YouTubeVideo[];}
export async function getYouTubeVideo(novelId:string,id:string){const{data,error}=await getSupabaseServerClient().from("youtube_videos").select("*").eq("novel_id",novelId).eq("id",id).maybeSingle(); if(error)throw error; return data as YouTubeVideo|null;}
export async function deleteYouTubeVideo(novelId:string,id:string){await getSupabaseServerClient().from("youtube_videos").delete().eq("novel_id",novelId).eq("id",id).throwOnError();}
export async function patchYouTubeVideo(novelId:string,id:string,patch:any){await getSupabaseServerClient().from("youtube_videos").update({...patch,updated_at:new Date().toISOString()}).eq("novel_id",novelId).eq("id",id).throwOnError();}

export async function buildYouTubeEvidence(novelId:string,input:any){const context=await getPlannerContext(novelId); const refs:any[]=[]; const evidence:string[]=[]; if(input.selected_entity_ids?.length){for(const e of context.entities.filter((x:any)=>input.selected_entity_ids.includes(x.id))){refs.push({type:"entity",id:e.id,summary:e.name}); evidence.push(`[entity] ${e.name}: ${e.description||""}`)}} if(input.selected_ai_report_ids?.length){for(const r of context.reports.filter((x:any)=>input.selected_ai_report_ids.includes(x.id))){refs.push({type:"ai_report",id:r.id,summary:r.title}); evidence.push(`[ai_report] ${r.title}: ${r.summary||""}`)}} if(input.selected_research_note_ids?.length){for(const n of context.notes.filter((x:any)=>input.selected_research_note_ids.includes(x.id))){refs.push({type:"research_note",id:n.id,summary:n.title}); evidence.push(`[research_note] ${n.title}: ${String(n.content||"").slice(0,500)}`)}} if(input.selected_content_idea_id){refs.push({type:"content_idea",id:input.selected_content_idea_id,summary:"Selected content idea"})} if(input.selected_script_id){const script=context.scripts.find((s:any)=>s.id===input.selected_script_id); if(script){refs.push({type:"video_script",id:script.id,summary:script.title}); evidence.push(`[script] ${script.title}: ${script.hook||""}`)}} if(input.topic)evidence.push(`[topic] ${input.topic}`); return {...context,evidence:evidence.join("\n\n"),source_references:refs,warnings:evidence.length?[]:["Không đủ dữ kiện trong nguyên tác"]};}

export async function generateLongForm(novelId:string,input:any){const evidence=await buildYouTubeEvidence(novelId,input); if(!evidence.evidence.trim()) throw new Error("Không đủ dữ kiện trong nguyên tác"); const json=parseJson(await createJsonChatCompletion({prompt:buildGenerateYouTubeLongFormPrompt({...input,...evidence})})); const scriptText=[json.hook,json.intro,...(json.sections||[]).map((s:any)=>s.script_text),json.conclusion,json.call_to_action].filter(Boolean).join("\n\n"); const id=await saveYouTubeVideo(novelId,{source_content_idea_id:input.selected_content_idea_id||null,source_script_id:input.selected_script_id||null,video_format:"long_form",title:json.title||input.topic,working_title:json.working_title||json.title,video_type:json.video_type||input.video_type||"custom",duration_target_minutes:Number(input.duration_target_minutes||json.duration_target_minutes||10),audience_level:input.audience_level||json.audience_level||"newbie",tone:input.tone||"mysterious",style:input.style||"cinematic_narration",script_text:scriptText,script_json:json,hook:json.hook,intro:json.intro,body:JSON.stringify(json.sections||[]),conclusion:json.conclusion,chapters_json:json.chapters||[],thumbnail_prompts_json:json.thumbnail_concepts||[],seo_metadata_json:json.seo_package||{},source_references_json:json.source_references?.length?json.source_references:evidence.source_references,fact_check_status:json.warnings?.length?"needs_review":"passed",visual_check_status:"passed",production_status:"script_ready"}); return {youtube_video_id:id,title:json.title,warnings:json.warnings||[]};}

export async function generateShort(novelId:string,input:any){const evidence=await buildYouTubeEvidence(novelId,input); const json=parseJson(await createJsonChatCompletion({prompt:buildGenerateYouTubeShortPrompt({...input,...evidence})})); const id=await saveYouTubeVideo(novelId,{source_script_id:input.selected_script_id||null,source_content_idea_id:input.selected_content_idea_id||null,video_format:"short",title:json.title||input.topic,video_type:json.video_type||"custom",duration_target_seconds:Number(input.duration_seconds||json.duration_target_seconds||60),audience_level:"newbie",tone:input.tone||"mysterious",style:"youtube_shorts",script_text:json.short_script,script_json:json,hook:json.hook,body:json.short_script,thumbnail_prompts_json:[json.thumbnail_frame_suggestion].filter(Boolean),source_references_json:json.source_references?.length?json.source_references:evidence.source_references,fact_check_status:json.warnings?.length?"needs_review":"passed",visual_check_status:"passed",production_status:"script_ready"}); return {youtube_video_id:id,title:json.title,warnings:json.warnings||[]};}

async function saveYouTubeVideo(novelId:string,payload:any){const{data,error}=await getSupabaseServerClient().from("youtube_videos").insert({novel_id:novelId,...payload}).select("id").single(); if(error)throw error; return data.id as string;}

export async function generateSeo(novelId:string,videoId:string,input:any){const video=await getYouTubeVideo(novelId,videoId); if(!video)throw new Error("Không tìm thấy YouTube video"); const json=parseJson(await createJsonChatCompletion({prompt:buildGenerateYouTubeSeoPackagePrompt({video,...input})})); const{data,error}=await getSupabaseServerClient().from("youtube_seo_packages").insert({youtube_video_id:videoId,novel_id:novelId,primary_title:json.primary_title||video.title,alternative_titles_json:json.alternative_titles||[],description:json.description,chapters_text:json.chapters_text,tags_json:json.tags||[],hashtags_json:json.hashtags||[],pinned_comment:json.pinned_comment,playlist_suggestion:json.playlist_suggestion,target_keywords_json:json.target_keywords||[],search_intent:json.search_intent,seo_score:clamp(json.seo_score),click_score:clamp(json.click_score),retention_score:clamp(json.retention_score),warning_notes_json:json.warnings||[]}).select("id").single(); if(error)throw error; await patchYouTubeVideo(novelId,videoId,{seo_metadata_json:json}); return data;}
export async function listSeo(novelId:string,videoId:string){const{data,error}=await getSupabaseServerClient().from("youtube_seo_packages").select("*").eq("novel_id",novelId).eq("youtube_video_id",videoId).order("created_at",{ascending:false}); if(error)throw error; return data;}

export async function generateThumbnails(novelId:string,videoId:string,input:any){const video=await getYouTubeVideo(novelId,videoId); const json=parseJson(await createJsonChatCompletion({prompt:buildGenerateYouTubeThumbnailPrompt({video,...input})})); const rows=(json.concepts||[]).slice(0,6).map((c:any)=>({youtube_video_id:videoId,novel_id:novelId,title:c.title||"Thumbnail",concept_summary:c.concept_summary,thumbnail_text:c.thumbnail_text,image_prompt:c.image_prompt,negative_prompt:c.negative_prompt,layout_type:c.layout_type||"cinematic_scene",emotion_angle:c.emotion_angle,visual_style_preset:c.visual_style_preset||"xianxia_cinematic",source_references_json:c.source_references||[],warning_notes_json:c.warning_notes||[]})); if(rows.length)await getSupabaseServerClient().from("youtube_thumbnail_concepts").insert(rows).throwOnError(); return {count:rows.length};}
export async function listThumbnails(novelId:string,videoId:string){const{data,error}=await getSupabaseServerClient().from("youtube_thumbnail_concepts").select("*").eq("novel_id",novelId).eq("youtube_video_id",videoId).order("created_at",{ascending:false}); if(error)throw error; return data;}

export async function repurposeToShorts(novelId:string,videoId:string,input:any){const video=await getYouTubeVideo(novelId,videoId); if(!video)throw new Error("Không tìm thấy video dài"); const json=parseJson(await createJsonChatCompletion({prompt:buildRepurposeLongFormToShortsPrompt({video,...input})})); const rows=(json.shorts||[]).slice(0,15).map((s:any)=>({youtube_video_id:videoId,novel_id:novelId,title:s.title,short_hook:s.short_hook,source_start_time:s.source_start_time,source_end_time:s.source_end_time,duration_seconds:Number(s.duration_seconds||input.duration_seconds||60),short_script:s.short_script,image_prompt:s.image_prompt,video_prompt:s.video_prompt,caption:s.caption,hashtags_json:s.hashtags||[],source_reference:s.source_reference||{},status:"script_ready"})); if(rows.length)await getSupabaseServerClient().from("youtube_shorts_cutdowns").insert(rows).throwOnError(); return {count:rows.length};}
export async function listShortsCutdowns(novelId:string,videoId:string){const{data,error}=await getSupabaseServerClient().from("youtube_shorts_cutdowns").select("*").eq("novel_id",novelId).eq("youtube_video_id",videoId).order("created_at",{ascending:false}); if(error)throw error; return data;}

export async function generatePlaylist(novelId:string,input:any){const evidence=await buildYouTubeEvidence(novelId,input); const json=parseJson(await createJsonChatCompletion({prompt:buildGenerateYouTubePlaylistPrompt({...evidence,...input})})); const rows=(json.playlists||[]).slice(0,5).map((p:any)=>({novel_id:novelId,title:p.title,description:p.description,playlist_type:p.playlist_type||"custom",target_audience:p.target_audience||"newbie",video_order_strategy:p.video_order_strategy||"beginner_to_advanced",status:"draft"})); if(rows.length)await getSupabaseServerClient().from("youtube_playlists").insert(rows).throwOnError(); return {count:rows.length};}
export async function listPlaylists(novelId:string){const{data,error}=await getSupabaseServerClient().from("youtube_playlists").select("*").eq("novel_id",novelId).order("created_at",{ascending:false}); if(error)throw error; return data;}

export async function generateChecklist(novelId:string,videoId:string){const video=await getYouTubeVideo(novelId,videoId); const json=parseJson(await createJsonChatCompletion({prompt:buildYouTubeUploadChecklistPrompt({video})})); const{data,error}=await getSupabaseServerClient().from("youtube_upload_checklists").insert({youtube_video_id:videoId,novel_id:novelId,checklist_json:json.checklist||[],overall_status:json.overall_status||"needs_review"}).select("id").single(); if(error)throw error; return data;}
export async function listChecklists(novelId:string,videoId:string){const{data,error}=await getSupabaseServerClient().from("youtube_upload_checklists").select("*").eq("novel_id",novelId).eq("youtube_video_id",videoId).order("created_at",{ascending:false}); if(error)throw error; return data;}

export async function patchYoutubeTable(table:string,novelId:string,id:string,patch:any){await getSupabaseServerClient().from(table).update({...patch,updated_at:new Date().toISOString()}).eq("novel_id",novelId).eq("id",id).throwOnError();}
export async function deleteYoutubeRow(table:string,novelId:string,id:string){await getSupabaseServerClient().from(table).delete().eq("novel_id",novelId).eq("id",id).throwOnError();}
function parseJson(value:string): any {return parseAIJson(value,"AI returned invalid JSON format") as any}
function clamp(v:any){const n=Number(v);return Math.max(1,Math.min(10,Number.isFinite(n)?Math.round(n):5))}
