"use client";
import { useState, useTransition } from "react";
import { Clipboard, ImageIcon, ListVideo, Loader2, PlaySquare, Search, Sparkles, SplitSquareVertical, Upload } from "lucide-react";
import type { YouTubeVideo } from "@/lib/module6-types";
const tabs=["Long-form Generator","Shorts Generator","Repurpose","SEO Package","Thumbnail Studio","Playlist Planner","Upload Checklist"] as const;
export function YouTubeStudioPage({novelId,initialVideos}:{novelId:string;initialVideos:YouTubeVideo[]}){const[tab,setTab]=useState<(typeof tabs)[number]>(tabs[0]);const[videos,setVideos]=useState(initialVideos);const[msg,setMsg]=useState("");const[loading,start]=useTransition();async function refresh(){const p=await fetch(`/api/novels/${novelId}/youtube/videos`).then(r=>r.json());setVideos(p.videos||[])}function run(fn:()=>Promise<any>,ok:string){setMsg("");start(async()=>{try{const p=await fn();if(p?.error)throw new Error(p.error);setMsg(ok);await refresh()}catch(e){setMsg(e instanceof Error?e.message:"Có lỗi")}})}return <div className="space-y-5"><YouTubeStudioTabs value={tab} onChange={setTab}/>{loading?<LoadingState/>:null}{msg?<div className="rounded-md border border-line bg-white p-3 text-sm">{msg}</div>:null}{tab==="Long-form Generator"?<LongFormGeneratorPanel novelId={novelId} run={run}/>:null}{tab==="Shorts Generator"?<YouTubeShortsGeneratorPanel novelId={novelId} videos={videos} run={run}/>:null}{tab==="Repurpose"?<RepurposeLongFormPanel novelId={novelId} videos={videos} run={run}/>:null}{tab==="SEO Package"?<YouTubeSeoPackagePanel novelId={novelId} videos={videos} run={run}/>:null}{tab==="Thumbnail Studio"?<ThumbnailStudioPanel novelId={novelId} videos={videos} run={run}/>:null}{tab==="Playlist Planner"?<PlaylistPlannerPanel novelId={novelId} run={run}/>:null}{tab==="Upload Checklist"?<YouTubeUploadChecklistPanel novelId={novelId} videos={videos} run={run}/>:null}<YouTubeVideoList videos={videos}/></div>}
export function YouTubeStudioTabs({value,onChange}:any){return <div className="flex flex-wrap gap-2 rounded-lg border border-line bg-white p-2 shadow-panel">{tabs.map(t=><button key={t} onClick={()=>onChange(t)} className={`h-10 rounded-md px-3 text-sm font-semibold ${value===t?"bg-ink text-white":"text-zinc-600 hover:bg-zinc-50"}`}>{t}</button>)}</div>}
function SelectVideo({videos,value,onChange}:{videos:YouTubeVideo[];value:string;onChange:(v:string)=>void}){return <select className="h-10 rounded-md border border-line px-3 text-sm" value={value} onChange={e=>onChange(e.target.value)}><option value="">Chọn YouTube video</option>{videos.map(v=><option key={v.id} value={v.id}>{v.title} ({v.video_format})</option>)}</select>}
export function LongFormGeneratorPanel({novelId,run}:any){const[topic,setTopic]=useState("");const[minutes,setMinutes]=useState(10);return <Panel title="YouTube Long-form Generator" icon={PlaySquare}><LongFormInputForm topic={topic} setTopic={setTopic} minutes={minutes} setMinutes={setMinutes}/><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/youtube/videos/generate-long-form`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,video_type:"lore_explainer",duration_target_minutes:minutes,audience_level:"newbie",tone:"mysterious",style:"cinematic_narration",structure_type:"lore_analysis"})}).then(r=>r.json()),"Đã tạo long-form YouTube.")} className="mt-3 h-10 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white">Generate Long-form</button></Panel>}
export function LongFormInputForm({topic,setTopic,minutes,setMinutes}:any){return <div className="grid gap-3 md:grid-cols-[1fr_120px]"><input className="h-10 rounded-md border border-line px-3 text-sm" placeholder="Chủ đề video dài..." value={topic} onChange={e=>setTopic(e.target.value)}/><select className="h-10 rounded-md border border-line px-3 text-sm" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}>{[5,8,10,15,20].map(m=><option key={m} value={m}>{m} phút</option>)}</select></div>}
export function YouTubeShortsGeneratorPanel({novelId,videos,run}:any){const[topic,setTopic]=useState("");const[script,setScript]=useState("");return <Panel title="YouTube Shorts Generator" icon={SplitSquareVertical}><input className="h-10 w-full rounded-md border border-line px-3 text-sm" placeholder="Chủ đề Shorts..." value={topic} onChange={e=>setTopic(e.target.value)}/><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/youtube/videos/generate-short`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,selected_script_id:script||null,duration_seconds:60,tone:"fast_viral",visual_style_preset:"xianxia_cinematic"})}).then(r=>r.json()),"Đã tạo YouTube Shorts.")} className="mt-3 h-10 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white">Generate Short</button></Panel>}
export function RepurposeLongFormPanel({novelId,videos,run}:any){const[id,setId]=useState("");return <Panel title="Repurpose Long-form to Shorts" icon={SplitSquareVertical}><SelectVideo videos={videos.filter((v: YouTubeVideo)=>v.video_format==="long_form")} value={id} onChange={setId}/><button disabled={!id} onClick={()=>run(()=>fetch(`/api/novels/${novelId}/youtube/videos/${id}/repurpose-to-shorts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({number_of_shorts:8,duration_seconds:60,strategy:"mixed"})}).then(r=>r.json()),"Đã tạo shorts cutdowns.")} className="mt-3 h-10 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white disabled:bg-zinc-300">Generate Shorts</button></Panel>}
export function YouTubeSeoPackagePanel({novelId,videos,run}:any){const[id,setId]=useState("");return <Panel title="SEO Package" icon={Search}><SelectVideo videos={videos} value={id} onChange={setId}/><button disabled={!id} onClick={()=>run(()=>fetch(`/api/novels/${novelId}/youtube/videos/${id}/seo/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title_style:"seo_balanced",description_style:"analysis"})}).then(r=>r.json()),"Đã tạo SEO package.")} className="mt-3 h-10 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white disabled:bg-zinc-300">Generate SEO</button></Panel>}
export function ThumbnailStudioPanel({novelId,videos,run}:any){const[id,setId]=useState("");return <Panel title="Thumbnail Studio" icon={ImageIcon}><SelectVideo videos={videos} value={id} onChange={setId}/><button disabled={!id} onClick={()=>run(()=>fetch(`/api/novels/${novelId}/youtube/videos/${id}/thumbnails/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({thumbnail_style:"dramatic_character",emotion_angle:"mystery",visual_style_preset:"xianxia_cinematic"})}).then(r=>r.json()),"Đã tạo thumbnail concepts.")} className="mt-3 h-10 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white disabled:bg-zinc-300">Generate Thumbnails</button></Panel>}
export function PlaylistPlannerPanel({novelId,run}:any){return <Panel title="Playlist Planner" icon={ListVideo}><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/youtube/playlists/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playlist_type:"lore_playlist",number_of_videos:10,target_audience:"newbie",order_strategy:"beginner_to_advanced"})}).then(r=>r.json()),"Đã tạo playlist.")} className="h-10 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white">Generate Playlist</button></Panel>}
export function YouTubeUploadChecklistPanel({novelId,videos,run}:any){const[id,setId]=useState("");return <Panel title="Upload Checklist" icon={Upload}><SelectVideo videos={videos} value={id} onChange={setId}/><button disabled={!id} onClick={()=>run(()=>fetch(`/api/novels/${novelId}/youtube/videos/${id}/upload-checklist/generate`,{method:"POST"}).then(r=>r.json()),"Đã tạo upload checklist.")} className="mt-3 h-10 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white disabled:bg-zinc-300">Generate Checklist</button></Panel>}
function YouTubeVideoList({videos}:{videos:YouTubeVideo[]}){return <section className="grid gap-3 xl:grid-cols-2">{videos.map(v=><article key={v.id} className="rounded-lg border border-line bg-white p-4 shadow-panel"><h3 className="font-semibold text-ink">{v.title}</h3><p className="mt-1 text-sm text-zinc-500">{v.video_format} · {v.video_type} · fact {v.fact_check_status} · visual {v.visual_check_status}</p><p className="mt-2 line-clamp-2 text-sm text-zinc-700">{v.hook}</p></article>)}{!videos.length?<EmptyState text="Chưa có video YouTube."/>:null}</section>}
function Panel({title,icon:Icon,children}:any){return <section className="rounded-lg border border-line bg-white p-5 shadow-panel"><h2 className="mb-4 flex items-center gap-2 font-semibold text-ink"><Icon className="h-4 w-4"/>{title}</h2>{children}</section>}
export function LongFormOutputViewer(){return null} export function SectionScriptCard(){return null} export function RetentionHookCard(){return null} export function YouTubeShortOutputViewer(){return null} export function ShortsSceneCard(){return null} export function ShortsCutdownCard(){return null} export function CutdownTimelinePreview(){return null} export function TitleVariantsCard(){return null} export function DescriptionViewer(){return null} export function ChaptersViewer(){return null} export function TagsViewer(){return null} export function PinnedCommentCard(){return null} export function ThumbnailConceptCard(){return null} export function ThumbnailPromptViewer(){return null} export function ThumbnailStyleSelector(){return null} export function PlaylistCard(){return null} export function PlaylistVideoOrderList(){return null} export function ChecklistCategoryCard(){return null} export function ChecklistStatusBadge(){return null} export function SourceReferenceList(){return null} export function WarningBox(){return null} export function CopyButton(){return null} export function ExportButton(){return null} function LoadingState(){return <div className="rounded-md bg-zinc-50 p-3 text-sm text-zinc-600"><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Đang xử lý...</div>} function EmptyState({text}:{text:string}){return <div className="rounded-lg border border-dashed border-line bg-white p-8 text-center text-sm text-zinc-500">{text}</div>} export function ErrorState(){return null}

