"use client";

import { useMemo, useState, useTransition } from "react";
import Link from "next/link";
import { CalendarDays, Check, ClipboardList, KanbanSquare, Lightbulb, Loader2, Plus, Sparkles } from "lucide-react";
import type { ContentCalendarItem, ContentIdea, ContentSeries, ProductionTask } from "@/lib/module5-types";

const tabs = ["Series Builder", "Idea Bank", "Content Calendar", "Production Board"] as const;
const statusColumns = ["idea", "approved", "script_generated", "recording", "editing", "scheduled", "published"];

export function ContentPlannerPage({ novelId, initialSeries, initialIdeas, initialCalendar, initialTasks }: { novelId: string; initialSeries: ContentSeries[]; initialIdeas: ContentIdea[]; initialCalendar: ContentCalendarItem[]; initialTasks: ProductionTask[] }) {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Series Builder");
  const [series, setSeries] = useState(initialSeries);
  const [ideas, setIdeas] = useState(initialIdeas);
  const [calendar, setCalendar] = useState(initialCalendar);
  const [tasks, setTasks] = useState(initialTasks);
  const [message, setMessage] = useState("");
  const [isPending, startTransition] = useTransition();

  async function refresh() {
    const [s, i, c, t] = await Promise.all([fetch(`/api/novels/${novelId}/series`).then(r=>r.json()), fetch(`/api/novels/${novelId}/ideas`).then(r=>r.json()), fetch(`/api/novels/${novelId}/calendar`).then(r=>r.json()), fetch(`/api/novels/${novelId}/production-tasks`).then(r=>r.json())]);
    setSeries(s.series || []); setIdeas(i.ideas || []); setCalendar(c.calendar_items || []); setTasks(t.tasks || []);
  }
  function run(action: () => Promise<any>, ok: string) { setMessage(""); startTransition(async () => { try { const payload = await action(); if (payload?.error) throw new Error(payload.error); setMessage(ok); await refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : "Có lỗi xảy ra."); } }); }

  return <div className="space-y-5"><ContentPlannerTabs value={tab} onChange={setTab} />{isPending ? <LoadingState text="Đang xử lý..." /> : null}{message ? <div className="rounded-md border border-line bg-white p-3 text-sm text-zinc-700">{message}</div> : null}{tab === "Series Builder" ? <SeriesBuilderPanel novelId={novelId} series={series} run={run} /> : null}{tab === "Idea Bank" ? <IdeaBankPage novelId={novelId} series={series} ideas={ideas} run={run} /> : null}{tab === "Content Calendar" ? <ContentCalendarPage novelId={novelId} series={series} ideas={ideas} calendar={calendar} run={run} /> : null}{tab === "Production Board" ? <ProductionBoardPage novelId={novelId} ideas={ideas} tasks={tasks} run={run} /> : null}</div>;
}

export function ContentPlannerTabs({ value, onChange }: { value: string; onChange: (v: any) => void }) { return <div className="flex flex-wrap gap-2 rounded-lg border border-line bg-white p-2 shadow-panel">{tabs.map((item) => <button key={item} onClick={() => onChange(item)} className={`h-10 rounded-md px-3 text-sm font-semibold ${value === item ? "bg-ink text-white" : "text-zinc-600 hover:bg-zinc-50"}`}>{item}</button>)}</div>; }

export function SeriesBuilderPanel({ novelId, series, run }: any) { const [count,setCount]=useState(3); return <div className="grid gap-4 xl:grid-cols-[340px_1fr]"><section className="rounded-lg border border-line bg-white p-5 shadow-panel"><h2 className="font-semibold text-ink">Generate Series</h2><GenerateSeriesForm count={count} setCount={setCount} onGenerate={() => run(() => fetch(`/api/novels/${novelId}/series/generate`, { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ channel_goal:"Làm kênh lore tiên hiệp", number_of_series:count, videos_per_series:10, target_audience:"newbie", tone:"mysterious", style:"tiktok_viral", default_duration_seconds:60 }) }).then(r=>r.json()), `Đã tạo series.`)} /></section><SeriesList novelId={novelId} series={series} run={run} /></div>; }
export function GenerateSeriesForm({ count, setCount, onGenerate }: any) { return <div className="mt-4 space-y-3"><input className="h-10 w-full rounded-md border border-line px-3 text-sm" type="number" min={1} max={10} value={count} onChange={(e)=>setCount(Number(e.target.value))} /><button onClick={onGenerate} className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-md bg-jade-700 text-sm font-semibold text-white"><Sparkles className="h-4 w-4" />Generate Series</button></div>; }
export function SeriesList({ novelId, series, run }: any) { return <section className="grid gap-3 xl:grid-cols-2">{series.map((item: ContentSeries) => <SeriesCard key={item.id} novelId={novelId} series={item} run={run} />)}{series.length===0?<EmptyState text="Chưa có series."/>:null}</section>; }
export function SeriesCard({ novelId, series, run }: any) { return <article className="rounded-lg border border-line bg-white p-5 shadow-panel"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-ink">{series.title}</h3><p className="mt-1 text-sm text-zinc-500">{series.series_type} · {series.total_planned_videos} videos</p></div><span className="rounded-md bg-zinc-100 px-2 py-1 text-xs font-semibold text-zinc-600">{series.status}</span></div><p className="mt-3 line-clamp-3 text-sm text-zinc-700">{series.description}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/ideas/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({series_id:series.id,number_of_ideas:5,video_type:"all",duration_seconds:60,target_audience:series.target_audience,tone:series.tone,style:series.style,source_scope:"all_entities"})}).then((r)=>r.json()),"Đã tạo ideas cho series.")} className="h-9 rounded-md bg-ink px-3 text-sm font-semibold text-white">Generate Ideas</button><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/series/${series.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"active"})}).then(r=>r.json()),"Đã active series.")} className="h-9 rounded-md border border-line px-3 text-sm font-semibold">Active</button></div></article>; }
export function SeriesDetailPanel(){return null;} export function SaveSeriesButton(){return null;}

export function IdeaBankPage({ novelId, series, ideas, run }: any) { const [q,setQ]=useState(""); const filtered=useMemo(()=>ideas.filter((i:ContentIdea)=>!q||`${i.title} ${i.topic}`.toLowerCase().includes(q.toLowerCase())),[ideas,q]); return <div className="space-y-4"><GenerateIdeasForm novelId={novelId} series={series} run={run}/><IdeaFilterBar query={q} onQueryChange={setQ}/><div className="grid gap-3 xl:grid-cols-2">{filtered.map((idea:ContentIdea)=><IdeaCard key={idea.id} novelId={novelId} idea={idea} run={run}/>)}</div>{filtered.length===0?<EmptyState text="Chưa có idea phù hợp."/>:null}</div>; }
export function GenerateIdeasForm({ novelId, series, run }: any) { const [seriesId,setSeriesId]=useState(""); const [n,setN]=useState(10); return <section className="grid gap-3 rounded-lg border border-line bg-white p-4 shadow-panel md:grid-cols-[1fr_120px_160px]"><select className="h-10 rounded-md border border-line px-3 text-sm" value={seriesId} onChange={e=>setSeriesId(e.target.value)}><option value="">Không chọn series</option>{series.map((s:ContentSeries)=><option key={s.id} value={s.id}>{s.title}</option>)}</select><input className="h-10 rounded-md border border-line px-3 text-sm" type="number" value={n} onChange={e=>setN(Number(e.target.value))}/><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/ideas/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({series_id:seriesId||null,number_of_ideas:n,video_type:"all",duration_seconds:60,target_audience:"newbie",tone:"mysterious",style:"tiktok_viral",source_scope:"all_entities"})}).then(r=>r.json()),"Đã tạo ideas.")} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-jade-700 text-sm font-semibold text-white"><Lightbulb className="h-4 w-4"/>Generate</button></section>; }
export function IdeaFilterBar({ query,onQueryChange }: any) { return <input className="h-10 w-full rounded-md border border-line px-3 text-sm" placeholder="Search title/topic..." value={query} onChange={e=>onQueryChange(e.target.value)} />; }
export function IdeaCard({ novelId, idea, run }: any) { return <article className="rounded-lg border border-line bg-white p-5 shadow-panel"><div className="flex items-start justify-between"><div><h3 className="font-semibold text-ink">{idea.title}</h3><p className="mt-1 text-sm text-zinc-500">{idea.video_type} · {idea.suggested_duration_seconds}s · {idea.series?.title||"No series"}</p></div><IdeaStatusBadge status={idea.status}/></div><p className="mt-3 text-sm text-zinc-700">{idea.hook_angle}</p><div className="mt-3 flex flex-wrap gap-2"><IdeaScoreBadge label="Priority" score={idea.priority_score}/><IdeaScoreBadge label="Viral" score={idea.viral_score}/><IdeaScoreBadge label="Evidence" score={idea.evidence_strength_score}/></div>{idea.warning_notes_json?.length?<WarningBox warnings={idea.warning_notes_json}/>:null}<div className="mt-4 flex flex-wrap gap-2"><ApproveIdeaButton onClick={()=>run(()=>fetch(`/api/novels/${novelId}/ideas/${idea.id}/approve`,{method:"POST"}).then(r=>r.json()),"Đã approve idea.")}/><GenerateScriptFromIdeaButton onClick={()=>run(()=>fetch(`/api/novels/${novelId}/ideas/${idea.id}/generate-script`,{method:"POST"}).then(r=>r.json()),"Đã tạo script từ idea.")}/><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/calendar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content_idea_id:idea.id,series_id:idea.series_id,publish_date:new Date().toISOString().slice(0,10),publish_time:"20:00",platform:"tiktok",title:idea.title,status:idea.status==="script_generated"?"asset_needed":"script_needed"})}).then(r=>r.json()),"Đã thêm vào calendar.")} className="h-9 rounded-md border border-line px-3 text-sm font-semibold">Add Calendar</button></div></article>; }
export function IdeaTable(){return null;} export function IdeaScoreBadge({label,score}:any){return <span className="rounded-md bg-zinc-100 px-2 py-1 text-xs font-semibold text-zinc-700">{label}: {score}/10</span>;} export function IdeaStatusBadge({status}:any){return <span className="rounded-md bg-jade-50 px-2 py-1 text-xs font-semibold text-jade-700">{status}</span>;} export function ApproveIdeaButton({onClick}:any){return <button onClick={onClick} className="inline-flex h-9 items-center gap-1 rounded-md bg-ink px-3 text-sm font-semibold text-white"><Check className="h-4 w-4"/>Approve</button>;} export function GenerateScriptFromIdeaButton({onClick}:any){return <button onClick={onClick} className="h-9 rounded-md border border-line px-3 text-sm font-semibold">Generate Script</button>;}
export function ContentCalendarPage({ novelId, series, ideas, calendar, run }: any) { return <div className="space-y-4"><GenerateCalendarForm novelId={novelId} ideas={ideas} run={run}/><CalendarListView calendar={calendar}/></div>; }
export function GenerateCalendarForm({ novelId, ideas, run }: any) { const today=new Date().toISOString().slice(0,10); return <section className="rounded-lg border border-line bg-white p-4 shadow-panel"><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/calendar/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({start_date:today,end_date:today,posts_per_day:1,preferred_publish_times:["20:00"],platforms:["tiktok"],selected_series_ids:[],selected_idea_ids:ideas.filter((i:any)=>i.status==="approved").slice(0,7).map((i:any)=>i.id),strategy:"balanced"})}).then(r=>r.json()),"Đã tạo calendar.")} className="inline-flex h-10 items-center gap-2 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white"><CalendarDays className="h-4 w-4"/>Generate Calendar</button></section>; }
export function CalendarListView({ calendar }: any) { return <div className="grid gap-3 xl:grid-cols-2">{calendar.map((item:any)=><CalendarItemCard key={item.id} item={item}/>) }{calendar.length===0?<EmptyState text="Chưa có lịch đăng."/>:null}</div>; }
export function CalendarItemCard({ item }: any) { return <article className="rounded-lg border border-line bg-white p-4 shadow-panel"><div className="flex items-start justify-between"><div><h3 className="font-semibold text-ink">{item.title}</h3><p className="mt-1 text-sm text-zinc-500">{item.publish_date} {item.publish_time} · {item.platform}</p></div><span className="rounded-md bg-zinc-100 px-2 py-1 text-xs font-semibold">{item.status}</span></div><p className="mt-2 text-sm text-zinc-600">{item.notes}</p></article>; }
export function CalendarMonthView(){return null;} export function CalendarWeekView(){return null;} export function CalendarFilterBar(){return null;} export function AddToCalendarButton(){return null;}

export function ProductionBoardPage({ novelId, ideas, tasks, run }: any) { return <div className="space-y-4"><button onClick={()=>run(()=>fetch(`/api/novels/${novelId}/production-tasks/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content_idea_id:ideas[0]?.id||null})}).then(r=>r.json()),"Đã tạo production tasks.")} className="inline-flex h-10 items-center gap-2 rounded-md bg-jade-700 px-3 text-sm font-semibold text-white"><ClipboardList className="h-4 w-4"/>Generate Tasks</button><KanbanBoard ideas={ideas} tasks={tasks}/></div>; }
export function KanbanBoard({ ideas, tasks }: any) { return <div className="grid gap-3 xl:grid-cols-4 2xl:grid-cols-7">{statusColumns.map(status=><div key={status} className="rounded-lg border border-line bg-white p-3 shadow-panel"><h3 className="mb-3 text-sm font-semibold text-ink">{status}</h3><div className="space-y-2">{ideas.filter((i:any)=>i.status===status).map((idea:any)=><ProductionCard key={idea.id} idea={idea} tasks={tasks.filter((t:any)=>t.content_idea_id===idea.id)}/>)}</div></div>)}</div>; }
export function ProductionCard({ idea, tasks }: any) { return <div className="rounded-md border border-line p-3 text-sm"><p className="font-semibold text-ink">{idea.title}</p><p className="mt-1 text-xs text-zinc-500">Tasks: {tasks.filter((t:any)=>t.status!=="done").length} còn lại</p></div>; }
export function ProductionTaskList({ tasks }: any) { return <div>{tasks.map((task:any)=><ProductionTaskCard key={task.id} task={task}/>)}</div>; } export function ProductionTaskCard({task}:any){return <div>{task.task_title}</div>;} export function GenerateTasksButton(){return null;} export function TaskStatusBadge(){return null;}

export function SourceReferenceList({ sources }: { sources: any[] }) { return <ul className="text-xs text-zinc-500">{sources?.map((s,i)=><li key={i}>{s.summary}</li>)}</ul>; }
export function WarningBox({ warnings }: { warnings: string[] }) { return <div className="mt-3 rounded-md border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">{warnings.map(w=><p key={w}>{w}</p>)}</div>; }
export function CopyButton(){return null;} export function LoadingState({ text }: { text: string }) { return <div className="rounded-md bg-zinc-50 p-3 text-sm text-zinc-600"><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>{text}</div>; } export function EmptyState({ text }: { text: string }) { return <div className="rounded-lg border border-dashed border-line bg-white p-8 text-center text-sm text-zinc-500">{text}</div>; } export function ErrorState({ text }: { text: string }) { return <div className="rounded-md border border-red-100 bg-red-50 p-3 text-sm text-red-700">{text}</div>; }
